#!/bin/bash

echo "This script demos 3 different ways to call another script. Derived from this: https://stackoverflow.com/a/8352939"
echo "====================================================================="
echo "Script-1 stuff:"
echo "====================================================================="
VAR_IN_1="I'm from script-1"
READ_FROM_1="YES!"
echo $VAR_IN_1
echo ""
echo "====================================================================="
echo "Script-2 stuff:"
echo "====================================================================="
# We can use another script in several ways:
## Option 1: This loads the contents of script-2 into script-1, which means variables and fns defined here are available to script 2:
## Vars here in script-1 *should* be available to script-2
echo `tput bold`Option 1: Load other script using source command:`tput sgr0`
echo "====================================================================="
source script-2

## Option 2: invoke script-2 using bash
## Vars here in script-1 should *not* be available to script-2
echo "====================================================================="
echo `tput bold`Option 2: Invoke using bash command:`tput sgr0`
echo "====================================================================="
bash ./script-2

## Option 3: add the other script to the PATH environment varialbe, then call it like a normal command
## Vars here in script-1 should *not* be available to script-2
echo "====================================================================="
echo `tput bold`Option 3: PATH Method:`tput sgr0`
echo "====================================================================="
PATH="$PATH:/c/Users/SnappyZappy/Desktop/Webzones/nix-stuff/scripts/script-calls-script/"
script-2
